- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE/release.md
- CHANGELOG.md
Modeled from https://github.com/ASFHyP3/hyp3-sdk
> Issue/PR Template + Changelog

- .github/workflows/test.yml
- README.md
- environment.yml
- isce2_topsapp/__init__.py
> Test and lint workflow

- isce2_topsapp/water_mask.py
Now use full res, land + ocean boundary mask uploaded to S3 by @jhkennedy.
Addresses #19
> Update water mask with full resolution GMT mask

- .gitignore
- isce2_topsapp/packaging.py
- tests/localize-data.ipynb
Resolves #35.
`gunw_id` for this repo: `S1-GUNW-A-R-064-tops-20210723_20210711-015000-00119W_00033N-PP-6267-v2_0_5`
`gunw_id` for asf prod : `S1-GUNW-D-R-071-tops-20191231_20191225-135307-33134N_31482N-PP-5b76-v2_0_2`
Added a cell in [`localize_data.ipynb`](https://github.com/ACCESS-Cloud-Based-InSAR/DockerizedTopsApp/blob/update-gunw-name/tests/localize-data.ipynb) to illustrate.
> Update GUNW Id name

- isce2_topsapp/__main__.py
- isce2_topsapp/json_encoder.py
This is for debugging previous jobs locally and can be useful for probing the `loc_data` dict in the main plugin workflow, i.e. https://github.com/ACCESS-Cloud-Based-InSAR/DockerizedTopsApp/blob/dev/isce2_topsapp/__main__.py#L69
> Record Localized Metadata to JSON

- isce2_topsapp/packaging_utils/nc_packaging.py
Products being created successfully but this error
is being ignored when packaging due to this exception handeling:
https://github.com/ACCESS-Cloud-Based-InSAR/DockerizedTopsApp/blob/02d2934794767038c2fe905616acf18d86bffaf8/isce2_topsapp/packaging_utils/nc_packaging.py#L601-L608
> Fix collections.Iterable error

- isce2_topsapp/localize_dem.py
Improves readability and stability of `dem-stitcher` call.
> Update localize_dem.py and expose keyword argument for pixel center CRS

- CHANGELOG.md
- isce2_topsapp/localize_dem.py
Addressed issue https://github.com/ACCESS-Cloud-Based-InSAR/DockerizedTopsApp/issues/60
> Round DEM bounds to nearest integer

- .trufflehog.txt
- CHANGELOG.md
- environment.yml
- isce2_topsapp/localize_dem.py
- isce2_topsapp/localize_slc.py
- isce2_topsapp/packaging.py
See https://github.com/ACCESS-Cloud-Based-InSAR/dem-stitcher/pull/49
> Update environment for dem-stitcher with new urls

- isce2_topsapp/__main__.py
- tests/test_main.py
Per our discussion in ASFHyP3/hyp3#1448
> drop --do-esd argument for gunw_slc entrypoint

- CHANGELOG.md
- environment.yml
Resolves #89. See https://github.com/ACCESS-Cloud-Based-InSAR/dem-stitcher/pull/54 for complete description.
> Fixes degenerate intersection of Tile Geometries in Dem-Stitcher

- CHANGELOG.md
- tests/prepare-for-delivery.ipynb
Shows how to add a "dummy" ionosphere layer to the GUNW product. Serves as a reminder how to do this and test additional layers that we may wish to add.
It's an "integration" test. It would be best to use the notebook diff tool to view it. Again, should improve these generally to run faster, but these are serving both to ensure correctness (in case they get edited) and how-to in terms of adding these layers.
> Illustrate how to add additional 2d layers

- .gitignore
- CHANGELOG.md
- isce2_topsapp/__main__.py
- isce2_topsapp/templates/topsapp_iono_template.xml
> Ionosphere - adding iono template

- CHANGELOG.md
- isce2_topsapp/__main__.py
See description in issue :point_down: 
fixes #106
> Add option to control OpenMP threads

- .gitignore
- CHANGELOG.md
- isce2_topsapp/solid_earth_tides.py
- tests/conftest.py
- tests/test_set.py
Resolves #148.
Before generating an orbit object in ISCE2, we ensure all state vectors are *unique* and *in order*. Duplicate state vectors produces zero derivative, which causes `nan` values in `geo2rdr`
> Fixes Orbit Creation for `geo2rdr`

- .github/workflows/test.yml
Per dependabot's suggestion in #163 - see Release Notes
> Update Test Workflow to Setup-micromamba

- CHANGELOG.md
- isce2_topsapp/localize_aux_cal.py
> Uses new aux cal location and removes nesting

- tests/localize-data.ipynb
- tests/solid_earth_tides.ipynb
- tests/test_main.py
Also fixes a flake8 error by removing a now-unused import.
> Update test notebooks that interact with orbits

- CHANGELOG.md
- README.md
- environment.yml
- isce2_topsapp/__main__.py
- isce2_topsapp/localize_orbits.py
- setup.py
- tests/localize-data.ipynb
- tests/solid_earth_tides.ipynb
- tests/test_main.py
- tests/test_notebooks.py
- tests/test_set.py
@asjohnston-asf - thanks.
We definitely don't need to keep `dry-run` - we were doing the bare minimum to update the plugin. There may be some tests that are required - can't tell.
Let's see if the tests pass.
> Thorough update of `s1_orbits`

- CHANGELOG.md
- isce2_topsapp/__init__.py
- isce2_topsapp/delivery_prep.py
- isce2_topsapp/localize_dem.py
- isce2_topsapp/localize_slc.py
- isce2_topsapp/packaging.py
- isce2_topsapp/packaging_utils/additional_layers.py
- isce2_topsapp/topsapp_proc.py
- setup.py
- tests/test_notebooks.py
Push only tracked changes from this PR:
https://github.com/ACCESS-Cloud-Based-InSAR/DockerizedTopsApp/pull/205
> Push only tracked changes
