environment.yml, isce2_topsapp/localize_dem.py
Fixes #22.
@gracebato - I tried this branch using the problematic pair. I believe it fixes.
Important notes:
- uses 0 for nodata areas
- The `gdal` metadata `nodata` is set to None.
```
isce2_topsapp --reference-scenes S1B_IW_SLC__1SDV_20211004T161549_20211004T161616_028988_037594_4DF8 --secondary-scenes S1A_IW_SLC__1SDV_20210928T161630_20210928T161657_039884_04B811_264A
```
Gets browse imagery
=> Update dem stitcher api

isce2_topsapp/__main__.py, isce2_topsapp/delivery_prep.py
Currently, this plugin will upload files to S3 like:
```shell
$ aws s3 ls --recursive --no-sign-request s3://hyp3-isce-contentbucket-4xpualmsjg98/a90f0ce8-e68d-4484-9a80-bf223d0067b3/
a90f0ce8-e68d-4484-9a80-bf223d0067b3/S1-GUNW-A-R-064-20210723-20210711-015000-119W_33N-f4d6-v2_0_5/S1-GUNW-A-R-064-20210723-20210711-015000-119W_33N-f4d6-v2_0_5.nc
a90f0ce8-e68d-4484-9a80-bf223d0067b3/S1-GUNW-A-R-064-20210723-20210711-015000-119W_33N-f4d6-v2_0_5/browse.png
a90f0ce8-e68d-4484-9a80-bf223d0067b3/S1-GUNW-A-R-064-20210723-20210711-015000-119W_33N-f4d6-v2_0_5/dataset.json
```
You can see the JSON HyP3 API resonse for this example job here: [a90f0ce8-e68d-4484-9a80-bf223d0067b3](https://hyp3-isce.asf.alaska.edu/jobs/a90f0ce8-e68d-4484-9a80-bf223d0067b3)
This changes it so files will be uploaded …
=> Simplify product delivery

isce2_topsapp/packaging_utils/isce_functions.py, isce2_topsapp/packaging_utils/makeGeocube.py
Resolves #46 in addition to:
- allowing `makeGeocube.py` to overwrite previous metadata files (for easier testing of this packaging)
- updates calls to pyproj to fix warning (this was suspected to be the source of the warning though was not).
The issue was with a non-standard geo-transform (see the issue ticket).
We can split this up into separate requests if desire (the addditional pieces are slightly unrelated).
The important change occurs in `isce_functions.py`, where during the update to the ISCE2 API, I remember the h5py API also required update and for some reason we used a non-sensical indexing. See the original file: https://github.com/aria-jpl/topsApp_pge/blob/develop/topsApp_utils/isce_functions.py#L382
Ultimately, in this request we are going to do the following additional test …
=> Updating Pyproj and fixing Georeferencing

environment.yml, isce2_topsapp/__main__.py, tests/test_main.py
HyP3 is moving to provide Earthdata credentials to the container via environment variables instead of CLI options to keep them encrypted throughout the processing chain.
=> Allow Earthdata credentials via environment variables

README.md
The environment builds fine with python>3.8... No need to explicitly restrict it to that in the readme.
=> Remove legacy instructions in Readme

CHANGELOG.md, isce2_topsapp/localize_aux_cal.py
Update the `aux-cal` urls to those found at https://sar-mpc.eu/ipf-adf/aux_cal/ (thank you, @ehavazli).
The new files required python `zipfile` to unpack, not `tarfile`.
Due to GIS issues, I used `gdal<3.4` and `python<3.10` on my mac. I believe this is not an issue on linux.
=> Update aux cal urls

CHANGELOG.md, README.md, environment.yml
Resolves #67. Simply updates `dem-stitcher` to `2.3.0` (see this [PR](https://github.com/ACCESS-Cloud-Based-InSAR/dem-stitcher/pull/35)), which, by default, resolves the filling for `glo_30` dem.
=> Glo 30 filling

.github/workflows/test.yml, .trufflehog.txt, CHANGELOG.md, README.md, environment.yml, isce2_topsapp/__init__.py, isce2_topsapp/__main__.py, isce2_topsapp/localize_burst.py, isce2_topsapp/localize_dem.py, isce2_topsapp/localize_slc.py, isce2_topsapp/packaging.py, isce2_topsapp/templates/topsapp_template.xml, isce2_topsapp/topsapp_proc.py, setup.py, tests/test_data/ref_manifest.xml, tests/test_data/sec_manifest.xml, tests/test_localize_burst.py, tox.ini
Unfortunately, this represents all the dem changes since May 2022, the burst prototype from Forrest and Joe, and all the things in between (aux cal url changes). I hope things don't break too much.
We need to really have hyp3 testing integrated. That would be a valuable and possibly fun hackathon.
Currently, we don't have suitable integration tests outside of manual inspection of the GUNWs with ARIA-Tools, which are important to ensure these products can be used for time-series analysis. I ran the dev-branch via in hyp3 using the job type`INSAR_ISCE_TEST` over Hawaii track 124, downloaded products, and was able successfully run `ariaTSsetup.py -f 'products/*.nc'`. This is of course grossly over simplified description, but I am sufficiently confident processing can continue.
I put a …
=> Dem-stitcher Updates and Burst Skeleton

isce2_topsapp/__main__.py, tests/test_main.py
As documented in the README, these arguments expect strings like `'True`'/`'False'`:
* `--estimate-ionosphere-delay`
* `--do-esd`
However, the argument parser uses a `bool` type for these arguments, which evaluates *any* non-empty string as `True`:
```python
>>> bool('true')
True
>>> bool('True')
True
>>> bool('False')
True
>>> bool('false')
True
>>> bool('foobar')
True
>>> bool('')
False
```
This adds a comparison function that can be used as a `type` for the argument parser and only returns true if the string `true` (any capitalization) is provided. 
```python
>>> string_is_true('true')
True
>>> string_is_true('True')
True
>>> string_is_true('False')
False
>>> string_is_true('false')
False
>>> bool('foobar')
False
>>> bool('')
False
```
in-line we the `False` default.
---
Note: Since …
=> fix boolean arguments in GUNW entrypoints

.github/dependabot.yml, .github/workflows/build.yml, .github/workflows/changelog.yml, .github/workflows/labeled-pr.yml, .github/workflows/release.yml, .github/workflows/static-analysis.yml, .github/workflows/tag.yml, .github/workflows/test.yml
Currently, the test build actions are failing because of an invalid workflow file:
ASFHyP3/Actions switch to micromamba in v0.7.0 and no longer needs to know that conda environment name, so this parameter is no longer valid. 
This PR:
* Drops `conda_env_name` from all workflows
* pins the ASFHyP3/Actions versions
* Adds dependabot to open PRs to update action versions
=> Update actions to use tags instead of `main`

CHANGELOG.md, isce2_topsapp/__main__.py, isce2_topsapp/packaging.py, tests/prepare-for-delivery.ipynb
Resolves #107. Ensures `1b` version attribute is changed to `1c`.
Not really sure about internals of different netcdf drivers and the implications. What caused the issue was that version attribute was read as `numpy.bytes_` with fixed length by `h5py`, whereas for `netCDF4` the same attribute was read as a string and length is variable. The fix using the former driver was to delete the attribute and overwrite it. Anyways, GUNWs are a decade in the making, so might be helpful why we are using so many different drivers.
Have a small notebook to illustrate the curiosity: https://gist.github.com/cmarshak/1822cd22fea0cc634cf026bfccbb4aa7
Added a test of the version update to ensure version update to `1c` going forward.
Also fixed the control flow, which was wrong because the version attribute …
=> Update Version Attribute

CHANGELOG.md, isce2_topsapp/localize_slc.py, tests/test_localize_slc.py
ISCE2 and this plugin have weird failures when there is not enough bursts over land.
This will simply raise a warning if there is at least 80% water (using a low resolution land mask from Natural Earth packaged with geopandas).
Seeing lots of failures for SLC pairs like this one: https://search.asf.alaska.edu/#/?searchType=List%20Search&searchList=S1B_IW_SLC__1SDV_20210731T153505_20210731T153532_028040_035848_C1F8&zoom=7.017&center=31.893,40.741&resultsLoaded=true&granule=S1B_IW_SLC__1SDV_20210731T153505_20210731T153532_028040_035848_C1F8-SLC
This is warning because there are edge cases where the low resolution mask misses small island areas (e.g. Catalina, Islands, and other coastal Southern California Islands). Hopefully will make debugging failures easier.
=> Raise warning when IFG extent has at least 80% water

CHANGELOG.md, isce2_topsapp/localize_slc.py
I recently renamed `intersection_geo` to `ifg_geo` since with frames dictating extents, the latter makes more sense. Not sure why this variable change (or lack of it) wasn't caught during tests/linting - but glad we have these integration tests.
=> Fix variable name error

CHANGELOG.md, isce2_topsapp/__main__.py, isce2_topsapp/solid_earth_tides.py, tests/solid_earth_tides.ipynb
Splits reference and secondary solid earth tide corrections into separate groups:
specifically
```
/science/grids/corrections/external/tides/solidEarth/reference
/science/grids/corrections/external/tides/solidEarth/secondary
```
=> Update Solid Earth Tide Correction to reference and secondary groups

.gitignore, CHANGELOG.md, isce2_topsapp/packaging.py, tests/midnight_crossing_metadata.json, tests/test_packaging.py
A GUNW ID looks like this:
```
S1-GUNW-D-R-048-tops-20230106_20221214-235959-00090E_00040N-PP-c254-v2_0_6
```
The `20230106` is the reference date and `20221214` is the secondary date. The `235959` is the center time i.e. `23:59:59`.
Previously the dates in the GUNW id were derived from start time. The center time was indeed the center time of a pass. In other words, these two date and time tokens were derived from _different_ datetimes and could be problematic if assuming not - i.e. using the GUNW ID to extract the metadata. This brought up in Raider [here](https://github.com/dbekaert/RAiDER/issues/488). You can see the current GUNW ID would be `[S1-GUNW-D-R-048-tops-20230106_20221214-000000-00090E_00040N-PP-c254-v2_0_6.nc](https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.ama …
=> Makes sure that the date and time in the GUNW ID are derived from center acquisition datetime

.github/workflows/test.yml, CHANGELOG.md, README.md, environment.yml
It appears 3.9 builds fine. We need to add 3.10 soon!
=> Remove python 3.8 support

CHANGELOG.md, isce2_topsapp/solid_earth_tides.py
Following our convo @cmarshak , I adjusted the logic of the SET code to handle and pass coordinates derived from the geotrans, as opposed to the latitude and longitude metadata arrays.
=> Solid Earth Tides: Pass coordinates from Geo Transforms to Pysolid, not lat/lon metadata arrays

.trufflehog.txt, CHANGELOG.md, isce2_topsapp/__init__.py, isce2_topsapp/__main__.py, isce2_topsapp/iono_proc.py, isce2_topsapp/localize_mask.py
Resolves #85.
Adding option to use water mask for ionospheric correction:
--      Ionospheric computation is done after topsApp run using ionoApp.xml
--      Iono_processiong runs in 5 steps: 
1. run ion step 'subband' (creation of lower and upper fine_interferograms for each burst)
2. transform (water) mask from geo to radar coordinate space, and us it to mask burst interferograms
3. run ion steps 'rawion' to 'esd' (computation and filtering of ionospheric correction)
4. create merged/topophase.ion (extracted from runMergeBursts.py)
5. run geocode for merged/topophase.ion
=> Iono workflow with masking

CHANGELOG.md, isce2_topsapp/__main__.py, isce2_topsapp/iono_proc.py, isce2_topsapp/localize_mask.py
Changes:
1. Skip iono_computation if lower/upper band unwrapped interferogram array is empty, i.e. all zeros. Return iono as zeros array
2. Skip downloading and using water mask if the AOI request is out of SWBD data coverage. TODO: introduce new water masks as mentioned in #135 : EXAMPLES: https://worldcover2021.esa.int/viewer or https://land.copernicus.eu/global/products/wb
3. fix few typos and add notes in the __main__ regarding the esd and calculation of burst jumps
=> Iono computation - addressing #135

CHANGELOG.md, isce2_topsapp/__main__.py, isce2_topsapp/iono_proc.py, isce2_topsapp/packaging.py, isce2_topsapp/packaging_utils/additional_layers.py
Adding ionosphere processing additional attribute to GUNW packging of ionosphere correction layer.
- Added attributes to ionosphere GUNW layer metadata:
1. ionosphere **processing_steps** - list:
a) iono-long wavelength: ['subband', 'rawion', 'filt_gaussian', 'geocode'],  
b) iono-long wavelength+az_shift per bursts: ['subband', 'rawion', 'filt_gaussian''ionosphere_shift', 'ion2grd', 'esd', 'geocode']
2. **water_mask** filename   str -. e.g. swbdLat_N47_N50_Lon_W072_W067.wbd (SRTM SWBD water mask)  or '' for None
3. **mask_connected_component_zero** flag - str(True/False): Mask out unwrapping connected component 0 after unwrapping lower and upper band
4. **do_phase_bridging** flag  - str(True/False): apply simple phase bridging between unwrapped components to minimize unwrapping error, …
=> adding iono processing attributes to GUNW

CHANGELOG.md, isce2_topsapp/localize_orbits.py, isce2_topsapp/solid_earth_tides.py
Resolves #145 - the subsequent error obtained locally (thanks @mgovorcin for graciously pointing this out!).
We fix it in a number of ways:
+ ensure the localized metadata dictionary has unique orbit xmls
+ ISCE2 orbit object is created with unique xmls of list passed
=> SET Bug related to geo2rdr (duplicate state vectors)

isce2_topsapp/delivery_prep.py
ASF's ingest workflow requires datetimes in the delivery metadata file to be formatted `2023-01-01T00:00:00.000000Z` per the schema at https://github.com/asfadmin/grfn-ingest/blob/test/verify/src/metadata_schema.json
[datetime.datetime.isoformat()](https://docs.python.org/3/library/datetime.html#datetime.datetime.isoformat) does not include microseconds if the microsecond value is exactly zero:
```
>>> datetime.datetime(2023, 1, 1, 0, 0, 0).isoformat()
'2023-01-01T00:00:00'
>>> datetime.datetime(2023, 1, 1, 0, 0, 0, 1).isoformat()
'2023-01-01T00:00:00.000001'
```
This PR eliminates the one-in-a-million case where `creation_timestamp` did not include microseconds, causing ingest to ASF to fail. We saw one instance of this in the recent processing campaign.
=> ensure creation_timestamp includes microseconds

CHANGELOG.md, README.md, environment.yml, isce2_topsapp/__main__.py, isce2_topsapp/localize_orbits.py, sample_run.sh, setup.py, tests/localize-data.ipynb, tests/prepare-for-delivery.ipynb, tests/solid_earth_tides.ipynb, tests/test_main.py, tests/test_notebooks.py, tests/test_set.py
This PR will upgrade to `hyp3lib` v2, which downloads orbit files from the new https://dataspace.copernicus.eu/ and requires that the appropriate credentials be provided.
TODO:
=> Upgrade to `hyp3lib` v2

CHANGELOG.md, isce2_topsapp/__init__.py, isce2_topsapp/iono_proc.py, isce2_topsapp/localize_dem.py, isce2_topsapp/packaging_utils/isce_functions.py, isce2_topsapp/packaging_utils/makeGeocube.py, isce2_topsapp/packaging_utils/nc_packaging.py, isce2_topsapp/topsapp_proc.py
Handling ISCE2 shenanigans in the `isce2_topsapp.__init__` before we import other parts of isce2_topsapp ensures we only have to do it once, no matter where we are in the package. Specifically, this:
* Ensures ISCE2 has already vomited its internals on the PYTHON_PATH: https://github.com/isce-framework/isce2/blob/main/__init__.py#L41-L44
* Resets the root logger back to WARNING so *every. single. package.* doesn't print debug statements
* Ensures the `applications` directory is on the system PATH
I additionally removed some unused imports I noticed.
=> Move isce2 shenanigans to __init__ so we only have to do it once

CHANGELOG.md, isce2_topsapp/packaging.py
* Update dataset version from `3.0.0` -> `3.0.1` to track products over areas processed during development of v3 product. In other words, large scale processing was done during v3 development but not all v3 products will be delivered to DAAC - we have standardized numerous attributes and layers.
=> Update dataset version to 3.0.1

.github/workflows/build.yml, CHANGELOG.md, environment.yml
Dem-stitcher's geoid urls became inactive this morning and needed to be changed.
See https://github.com/ACCESS-Cloud-Based-InSAR/dem-stitcher/issues/96
=> Update environment.yml for geoid update

CHANGELOG.md, README.md, environment.yml, isce2_topsapp/__main__.py, isce2_topsapp/localize_orbits.py, setup.py, tests/test_main.py, tests/test_notebooks.py, tests/test_set.py
Here's a more thorough orbit cleanup to consider. Using the s1-orbits package means hyp3lib is not longer needed as a dependency, and the esa username/password parameters are no longer required as inputs.
I don't fully appreciate the `dry_run` parameter; is it important that no orbit files be downloaded to disk when doing a dry run?
The test notebooks include code/instructions for setting up esa credentials and downloading orbits that still deserve to be updated. I'm opening the PR because I've been noodling on it today, but I'm not committed to doing the remaining work.
=> Adopt s1-orbits and remove esa credentials/hyp3lib 

isce2_topsapp/localize_slc.py, tests/test_localize_slc.py
DockerizedTopsApp does not (yet) support processing S1C scenes, so we need to exclude these from search results when querying SLCs for the given reference/secondary dates.
=> do not include S1C when querying SLCs for given reference/secondary date

CHANGELOG.md, environment.yml, isce2_topsapp/__init__.py, isce2_topsapp/__main__.py, isce2_topsapp/localize_slc.py, setup.py, tests/test_localize_slc.py
I selected 20 GUNW products at random from the ASF archive:
```
S1-GUNW-A-R-004-tops-20190406_20181008-230705-00079W_00037N-PP-f28d-v3_0_0.nc
S1-GUNW-A-R-005-tops-20231206_20231031-004312-00101W_00027N-PP-3746-v3_0_1.nc
S1-GUNW-A-R-035-tops-20150617_20150524-020742-00124W_00037N-PP-c22b-v3_0_1.nc
S1-GUNW-A-R-035-tops-20181017_20180713-020737-00124W_00038N-PP-eee9-v3_0_1.nc
S1-GUNW-A-R-035-tops-20190930_20180701-020808-00125W_00041N-PP-2364-v3_0_1.nc
S1-GUNW-A-R-048-tops-20211218_20210609-233133-00085W_00036N-PP-93fa-v3_0_0.nc
S1-GUNW-A-R-048-tops-20240313_20240218-233052-00084W_00033N-PP-c6e7-v3_0_1.nc
S1-GUNW-A-R-064-tops-20211220_20201125-015422-00123W_00047N-PP-3fd8-v3_0_1.nc
S1-GUNW-A-R-081-tops-20200915_20200903-070645-00174E_00040S-PP-364e-v3_0_1.nc …
```
=> Release v0.6.0

README.md, setup.py
#214 was merged during a [github incident](https://www.githubstatus.com/incidents/y7lb2rg4btd7) and no github actions ran as a result. This subsequent push to main should trigger the build of the production docker container and generation of the github release.
=> trigger v0.6.0 release
